version: '3.8'

services:
  files:
    image: files
    volumes:
      - /data/dumps/path:/input # change /data/dumps/path to the location of the RDF data dumps, make sure to add the dumps to files/config.json as well
      - fragments_volume:/output
    build:
      context: ./files

  server:
    image: server
    volumes:
      - fragments_volume:/usr/share/nginx/html
    ports:
      - "80:80"
    build:
      context: ./server

volumes:
  fragments_volume:
    external: true
